---

- hosts: all
  become: true
  tasks:

  - name: Update repositories
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php to apache2
    apt:
      name: libapache2-mod-php
      state: latest

